[pytest]
pythonpath = src
testpaths = src/test
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestUnraisableExceptionWarning
addopts = -v --strict-markers
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI tests
    api: API tests
    slow: Slow tests