[pytest]
pythonpath = src
testpaths = src/test
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestUnraisableExceptionWarning
addopts = -v --strict-markers